#!/usr/bin/env python

#make a check for python verion
#need to cleanup threads, can't quick restart
'''
Created on Jun 14, 2010

@modified: Jun 14, 2010
@author: Dale Hamel
@contact: umhameld@cc.umanitoba.ca
'''

#boot strapper imports
import lib,sys,os
from lib import boot_strap

	
def main(request):
	def printHelp():
		debug.log("Available actions:",actions=actions)
	
	import debug 
	import cmds
	

	actions=("help","sync","userconf","_handhold")

	debug.label("Bootstrapping completed")
	debug.log("Got request: ",request=request)

	from gitlib import GKRepo

	pathname=os.path.dirname(sys.argv[0])
	abspath= os.path.abspath(pathname)
	repo=GKRepo(abspath)

	#todo: add config check for default config options	
	if (len(request)!=0):
		action=request[0]

		if(len(request)>1):
			arguments=request[1:]	
		else:
			arguments=None

		if(action=="configure"):
			cmds.gitConfigSetup(repo,args)
		elif(action=="sync"):
			cmds.safeSyncBranch(repo,args)
		elif(action=="ignore"):
			cmds.ignoreExpression(repo,args)
		elif(action=="help"):
			printHelp()
		elif(action=="_handhold"):
			cmds._handHold(repo)		
		else:
			cmds._handHold(repo)		
	

			

def init_boot_strap():
	boot_strap(main)


if __name__ == "__main__":
	init_boot_strap()
