#!/usr/bin/env python

#make a check for python verion
#need to cleanup threads, can't quick restart
'''
Created on Jun 14, 2010

@modified: Jun 14, 2010
@author: Dale Hamel
@contact: umhameld@cc.umanitoba.ca
'''

#boot strapper imports
import lib,sys,os
from lib import boot_strap

	
def main(request):
	def printHelp():
		debug.log("Available actions:",actions=actions)
	
	import debug 
	import cmds
	

	actions=("help","sync","userconf")

	debug.label("Bootstrapping completed")
	debug.log("Got request: ",request=request)

	from gitlib import Repo
	pathname=os.path.dirname(sys.argv[0])
	abspath= os.path.abspath(pathname)
	repo=Repo(abspath)

	#todo: add config check for default config options	
	if (len(request)!=0):
		action=request[0]
		try:
			arg1=request[1]
			args=request[1:]
		except:
			arg1=str()
			args=list()
		
		if(action=="configure"):
			cmds.gitConfigSetup(repo)
		elif(action=="sync"):
			cmds.syncBranch(repo,branch=arg1)
		elif(action=="ignore"):
			cmds.ignoreExpression(arg1)
		elif(action=="help"):
			printHelp()
	
			
	else:
		debug.abort("Nothing to do")


def init_boot_strap():
	boot_strap(main)


if __name__ == "__main__":
	init_boot_strap()
